env:
  NPM_TOKEN: ENCRYPTED[bff12fafd99423fb6c275d2385d25845549d7285b66525df3107ae23a816f39254d77705f0cac21a151334b9e9b67c6a]

linux_build_and_publish_task:
  container:
    dockerfile: Dockerfile
  env:
    matrix:
      OCAML_VERSION: 4.02.3
      OCAML_VERSION: 4.04.2
      OCAML_VERSION: 4.06.1
      OCAML_VERSION: 4.07.1
  build_script: ./build.sh $OCAML_VERSION
  publish_script: ./publish.sh $OCAML_VERSION
  binaries_artifacts:
    path: "*.tgz"

mac_build_and_publish_task:
  osx_instance:
    image: mojave-base
  env:
    matrix:
      OCAML_VERSION: 4.02.3
      OCAML_VERSION: 4.04.2
      OCAML_VERSION: 4.06.1
      OCAML_VERSION: 4.07.1
  prepare_script:
    - brew install curl gpatch node git coreutils findutils
    - npm i -g esy@latest
  build_script: ./build.sh $OCAML_VERSION
  binaries_artifacts:
    path: "*.tgz"
